# Set the build language to Python
language: python
# Set the python version to 2.7
python:
  - "2.7"
  - "3.5"
virtualenv:
  system_site_packages: true

# Run the unit test
script:
  - coverage run tests/tests.py